version: '3.8'

services:
  postgres:
  container_name: hackaton-pg
  image: postgres
  ports:
  -5432:5432
  environment:
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: senha
  POSTGRES_DB: hackaton
  volumes:
  - ./data/pg:/data/postgres
